# Generated by Django 5.1.7 on 2025-03-20 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='단원 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='문제 코드')),
                ('topic', models.CharField(max_length=100, verbose_name='주제')),
                ('question_text', models.TextField(verbose_name='질문 내용')),
                ('answer_text', models.TextField(blank=True, help_text='주관식 문제일 경우 모범 답안을 입력합니다.', verbose_name='모범 답안')),
                ('keywords', models.TextField(blank=True, help_text='쉼표(,)로 구분하여 입력', verbose_name='주요 키워드')),
                ('question_type', models.CharField(choices=[('objective', '객관식'), ('subjective', '주관식')], max_length=20, verbose_name='문제 유형')),
                ('is_tail_question', models.BooleanField(default=False, verbose_name='꼬리 질문 여부')),
                ('explanation', models.TextField(blank=True, verbose_name='해설')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tokcs.chapter', verbose_name='단원')),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_questions', to='tokcs.quizquestion', verbose_name='부모 질문')),
            ],
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='선택지 내용')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답 여부')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='tokcs.quizquestion', verbose_name='문제')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='답안 내용')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='제출 시각')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='점수')),
                ('graded', models.BooleanField(default=False, verbose_name='채점 완료 여부')),
                ('feedback', models.TextField(blank=True, verbose_name='채점 피드백')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokcs.quizquestion', verbose_name='문제')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tokcs.quizchoice', verbose_name='선택한 보기')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]
