# Generated by Django 5.1.7 on 2025-03-20 14:49

import django.db.models.deletion
import tokcs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokcs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='주제')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='topic',
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=0, verbose_name='순서'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='단원 이름'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='topic',
            field=models.ForeignKey(default=tokcs.models.get_default_topic, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='tokcs.topic', verbose_name='주제'),
        ),
    ]
