# Generated by Django 5.1.7 on 2025-03-25 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokcs', '0003_quizquestion_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tokcs.topic', verbose_name='주제'),
        ),
    ]
