# Generated by Django 5.1.7 on 2025-03-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokcs', '0005_dailyquizpool_objectiveanswer_subjectiveanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailyquiz',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
